name: pawsandpixels
description: "Dog breed identification"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.2.4 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.2.1
  image_picker: ^1.1.0
  tflite_v2: 1.0.0
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - android/app/src/main/assets/
